<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'

const props = defineProps<{
  initialCode?: string;
  title?: string;
}>()

const code = ref(props.initialCode || '')
const slotRef = ref<HTMLElement | null>(null)

onMounted(() => {
  if (slotRef.value && !props.initialCode) {
    // Look for code or pre tags which might be generated by markdown
    const codeTag = slotRef.value.querySelector('code') || slotRef.value.querySelector('pre')
    const content = codeTag ? (codeTag.innerText || codeTag.textContent) : (slotRef.value.innerText || slotRef.value.textContent)
    if (content) {
      code.value = content.trim()
    }
  }
})

const output = ref<string[]>([])
const isRunning = ref(false)
let worker: Worker | null = null

const runCode = () => {
  if (isRunning.value) return
  isRunning.value = true
  output.value = ["Initializing execution environment..."]

  // We need a worker that has SciMathJS loaded
  // For now, let's use a simpler approach or create a dedicated playground worker
  worker = new Worker(new URL('../workers/playground.worker.ts', import.meta.url), { type: 'module' })

  worker.onmessage = (e) => {
    const { type, data } = e.data

    const formatResult = (res: any): string => {
      if (res === null || res === undefined) return 'undefined'
      if (ArrayBuffer.isView(res)) {
        const arr = Array.from(res as any).slice(0, 50)
        const truncated = (res as any).length > 50 ? '... ' : ''
        return `[ ${arr.map(v => typeof v === 'number' ? v.toFixed(4) : String(v)).join(', ')}${truncated} ]`
      }
      if (Array.isArray(res)) {
        const arr = res.slice(0, 50)
        const truncated = res.length > 50 ? '... ' : ''
        return `[ ${arr.map(v => typeof v === 'number' ? v.toFixed(4) : String(v)).join(', ')}${truncated} ]`
      }
      if (typeof res === 'object') {
        try {
          return JSON.stringify(res, null, 2)
        } catch {
          return String(res)
        }
      }
      return String(res)
    }

    if (type === 'log') {
      output.value.push(data)
    } else if (type === 'result') {
      output.value.push(`Result: ${formatResult(data)}`)
      isRunning.value = false
      worker?.terminate()
    } else if (type === 'error') {
      output.value.push(`Error: ${data}`)
      isRunning.value = false
      worker?.terminate()
    }
  }

  worker.postMessage({ type: 'execute', code: code.value })
}

onUnmounted(() => worker?.terminate())

</script>

<template>
  <div class="playground-container">
    <div class="playground-header">
      <span class="playground-title">{{ title || 'Interactive Lab' }}</span>
      <button @click="runCode" :disabled="isRunning" class="run-btn">
        {{ isRunning ? 'RUNNING...' : 'RUN CODE' }}
      </button>
    </div>
    <div class="playground-main">
      <div v-show="false" ref="slotRef">
        <slot></slot>
      </div>
      <div class="editor-section">
        <textarea v-model="code" class="code-editor" spellcheck="false"></textarea>
      </div>
      <div class="output-section">
        <div class="output-label">OUTPUT</div>
        <div class="output-console custom-scroll">
          <div v-for="(line, i) in output" :key="i" class="output-line">
            <span class="prompt">></span> {{ line }}
          </div>
          <div v-if="output.length === 0" class="output-placeholder">Hit RUN to execute...</div>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.playground-container {
  background: rgba(13, 17, 23, 0.8);
  border: 1px solid rgba(0, 242, 255, 0.2);
  border-radius: 12px;
  overflow: hidden;
  margin: 2rem 0;
  backdrop-filter: blur(10px);
  box-shadow: 0 10px 30px rgba(0, 0, 0, 0.5);
}

.playground-header {
  background: rgba(0, 242, 255, 0.05);
  padding: 0.75rem 1.5rem;
  display: flex;
  justify-content: space-between;
  align-items: center;
  border-bottom: 1px solid rgba(255, 255, 255, 0.05);
}

.playground-title {
  font-family: 'Outfit', sans-serif;
  font-weight: 600;
  letter-spacing: 1px;
  color: #00f2ff;
  font-size: 0.9rem;
  text-transform: uppercase;
}

.run-btn {
  background: linear-gradient(135deg, #3b82f6 0%, #00f2ff 100%);
  border: none;
  padding: 0.5rem 1.25rem;
  border-radius: 6px;
  color: white;
  font-weight: bold;
  font-size: 0.8rem;
  cursor: pointer;
  transition: all 0.2s ease;
  box-shadow: 0 0 15px rgba(0, 242, 255, 0.3);
}

.run-btn:hover:not(:disabled) {
  transform: translateY(-1px);
  box-shadow: 0 0 25px rgba(0, 242, 255, 0.5);
}

.run-btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.playground-main {
  display: grid;
  grid-template-columns: 1.5fr 1fr;
  min-height: 300px;
}

@media (max-width: 768px) {
  .playground-main {
    grid-template-columns: 1fr;
  }
}

.editor-section {
  border-right: 1px solid rgba(255, 255, 255, 0.05);
}

.code-editor {
  width: 100%;
  height: 100%;
  background: transparent;
  border: none;
  padding: 1.5rem;
  color: #e6edf3;
  font-family: 'Fira Code', 'Courier New', monospace;
  font-size: 0.9rem;
  line-height: 1.6;
  resize: vertical;
  outline: none;
  min-height: 250px;
}

.output-section {
  display: flex;
  flex-direction: column;
  background: rgba(0, 0, 0, 0.2);
}

.output-label {
  font-size: 0.7rem;
  font-weight: bold;
  color: rgba(255, 255, 255, 0.3);
  padding: 0.5rem 1rem;
  border-bottom: 1px solid rgba(255, 255, 255, 0.05);
}

.output-console {
  flex: 1;
  padding: 1rem;
  font-family: 'Fira Code', monospace;
  font-size: 0.85rem;
  overflow-y: auto;
  max-height: 300px;
}

.output-line {
  margin-bottom: 0.4rem;
  word-break: break-all;
}

.prompt {
  color: #00f2ff;
  margin-right: 0.5rem;
}

.output-placeholder {
  color: rgba(255, 255, 255, 0.2);
  font-style: italic;
  display: flex;
  align-items: center;
  justify-content: center;
  height: 100%;
}

.custom-scroll::-webkit-scrollbar {
  width: 6px;
}
.custom-scroll::-webkit-scrollbar-track {
  background: transparent;
}
.custom-scroll::-webkit-scrollbar-thumb {
  background: rgba(255, 255, 255, 0.1);
  border-radius: 3px;
}
.custom-scroll::-webkit-scrollbar-thumb:hover {
  background: rgba(255, 255, 255, 0.2);
}
</style>
